name: image_to_ascii
description: A Dart package to convert images to ASCII art.
version: 0.0.1
# repository: https://github.com/ericbreh/image_to_ascii

environment:
  sdk: ^3.7.0

dependencies:
  image: ^3.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
